name: som_env
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - aom=3.9.1=h7bae524_0
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=he0f2337_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - contourpy=1.3.2=py310h7f4e7e6_0
  - cycler=0.12.1=pyhcf101f3_2
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=h3ff7a7c_1
  - farama-notifications=0.0.4=pyhd8ed1ab_0
  - ffmpeg=8.0.1=gpl_h1511fcb_109
  - filelock=3.20.3=pyhd8ed1ab_0
  - fluidsynth=2.5.2=h2ab8666_0
  - fmt=12.1.0=h403dcb5_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310hf4fd40f_0
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.44.4=h7542897_0
  - giflib=5.2.2=h93a5062_0
  - glslang=16.1.0=h60b4770_0
  - gmp=6.3.0=h7bae524_2
  - graphite2=1.3.14=hec049ff_2
  - gymnasium=1.2.2=np2py310hcd98a52_0
  - gymnasium-classic_control=1.2.2=py310h43e8e4d_0
  - harfbuzz=12.3.0=h3103d1b_0
  - icu=78.2=h38cb7af_0
  - jax-jumpy=1.0.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - kaldi=5.5.1172=cpu_h999d4ea_3
  - kiwisolver=1.4.9=py310h563d721_2
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.18=hdfa7624_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libass=0.17.4=hcbd7ca7_0
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcxx=21.1.8=hf598326_0
  - libde265=1.0.15=h2ffa867_0
  - libdeflate=1.25=hc11a715_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libflac=1.5.0=h6824b09_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libglib=2.86.3=hfe11c1f_0
  - libheif=1.19.7=gpl_h79e6334_100
  - libhwloc=2.12.2=default_ha3cc4f2_1000
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblapacke=3.11.0=5_h1b118fd_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libmad=0.15.1b=h1a8c8d9_1001
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopenvino=2025.4.1=he5d468a_0
  - libopenvino-arm-cpu-plugin=2025.4.1=he5d468a_0
  - libopenvino-auto-batch-plugin=2025.4.1=h0b5e12f_0
  - libopenvino-auto-plugin=2025.4.1=h0b5e12f_0
  - libopenvino-hetero-plugin=2025.4.1=hf51539c_0
  - libopenvino-ir-frontend=2025.4.1=hf51539c_0
  - libopenvino-onnx-frontend=2025.4.1=h9101cd2_0
  - libopenvino-paddle-frontend=2025.4.1=h9101cd2_0
  - libopenvino-pytorch-frontend=2025.4.1=haf25636_0
  - libopenvino-tensorflow-frontend=2025.4.1=h6089731_0
  - libopenvino-tensorflow-lite-frontend=2025.4.1=haf25636_0
  - libopus=1.6.1=h1a92334_0
  - libpng=1.6.54=h132b30e_0
  - libprotobuf=6.31.1=h98f38fd_4
  - librsvg=2.60.0=h5c55ec3_0
  - libsndfile=1.2.2=hf95f74e_2
  - libsqlite=3.51.1=h1b79a29_1
  - libtiff=4.7.1=h4030677_1
  - libtorch=2.9.1=cpu_generic_h812a54d_3
  - libusb=1.0.29=hbc156a2_0
  - libuv=1.51.0=h6caf38d_1
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.15.2=ha759d40_0
  - libvulkan-loader=1.4.328.1=h49c215f_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h8d039ee_1
  - libxml2-16=2.15.1=h5ef1a60_1
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.8=h4a912ad_0
  - markupsafe=3.0.3=py310hf4fd40f_0
  - matplotlib=3.10.8=py310hb6292c7_0
  - matplotlib-base=3.10.8=py310h0181960_0
  - minisom=2.3.5=pyhff2d567_0
  - mpg123=1.32.9=hf642e45_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - networkx=3.4.2=pyh267e887_2
  - nomkl=1.0=h5ca1d4c_0
  - numpy=2.2.6=py310h4d83441_0
  - openfst=1.8.4=ha393de7_1
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.1=hd24854e_1
  - optree=0.18.0=py310h0e897d2_0
  - opusfile=0.12=h5643135_2
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h25f4b65_1
  - pango=1.56.4=h875632e_0
  - pcre2=10.47=h30297fc_0
  - pillow=12.1.0=py310hc037f36_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - portaudio=19.7.0=h5833ebf_0
  - portmidi=2.0.8=haf25636_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pugixml=1.15=hd3d436d_0
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-abi=11=hc364b38_1
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pygame=2.6.1=py310h3944dc2_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - python=3.10.19=hcd7f573_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=6_cp310
  - pytorch=2.9.1=cpu_generic_py310_h7e4ae62_3
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - rav1e=0.7.1=h0716509_3
  - readline=8.3=h46df422_0
  - scikit-learn=1.7.2=py310h660f142_0
  - scipy=1.15.2=py310h32ab4ed_0
  - sdl2=2.32.56=h248ca61_0
  - sdl2_image=2.8.2=h376e2e1_1
  - sdl2_mixer=2.6.3=h45fadf6_2
  - sdl2_ttf=2.24.0=h443c5de_0
  - sdl3=3.2.30=h6fa9c73_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.5=h1a5098f_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - snappy=1.2.2=hada39a4_1
  - spirv-tools=2025.4=ha7d2532_0
  - svt-av1=3.1.2=h12ba402_0
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2022.3.0=h4ddebb9_2
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_3
  - torchaudio=2.9.1=cpu_py310h2d14aa3_0
  - torchcodec=0.8.1=cpu_py310_h5e15f87_3
  - torchvision=0.24.1=cpu_py310_hb5240fb_1
  - torchvision-extra-decoders=0.0.2=py310h595f624_5
  - tornado=6.5.4=py310hfe3a0ae_0
  - tqdm=4.67.3=pyh8f84b5b_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.0=py310hfe3a0ae_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - zlib-ng=2.3.2=hed4e4f5_1
  - zstd=1.5.7=hbf9d68e_6
prefix: /Users/vardg/miniforge3/envs/som_env
